### PR TITLE
add workaround to year issue

### PR DESCRIPTION
**Pull request by Karyatis**

### CODE REVIEW

**Comment by Karyatis** [comment]
@mechamanny submitting for code review

**Comment by mechamanny** [comment]
Hey @Karyatis! This PR does not include the whole file. Did you want me to only review these changes?

**Comment by Karyatis** [comment]
@mechamanny: Woops. Meant to have the whole thing reviewed. 

https://github.com/Karyatis/phase-0-tracks/blob/master/ruby/vampires.rb

**Comment by mechamanny** [comment]
Notes: 

Some stray `p` statements on lines 36 and 38. 

`else` does not take a conditional, any time you do something like line 37 it is not getting evaluated, so not necessary to write.

59,61 can be combined using `||`

In your tests, you can write `actual_age` or `!actual_age` instead of `== true or false` since they are boolean values already.

**Pull request merged**
